openapi: 3.0.0
info:
  title: 'People Management System API'
  description: 'API for a people_management_system.'
  contact:
    name: Henry Steinhauer
    email: Henrysteinhauer@t-online.de
    url: https://github.com/H3nSte1n
  version: '1.0.0'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /api/v1/persons:
    get:
      tags:
        - Persons Administration
      summary: Gets all Personens
      description: Get a list of all Persons. The list supports pagination.
      parameters:
        - in: query
          name: pageSize
          description: Persons per Page
          schema:
            type: integer
        - name: pageNumber
          in: query
          description: Page number
          schema:
            type: integer
      responses:
        '200':
          description: Returns the selected Person.
          content:
            application/json:
              allOf:
                - $ref: './components/person.yml#definitions/Person'
                - $ref: './components/person.yml#definitions/Person--extended'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
    post:
      tags:
        - Persons Administration
      summary: Creates a Person
      description: Adds a new person to the person list.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components/person.yml#definitions/Person'
      responses:
        '201':
          description: Create new Person
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './components/person.yml#definitions/Person'
                  - $ref: './components/person.yml#definitions/Person--extended'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
  /api/v1/persons/{person_id}:
    get:
      tags:
        - Persons Administration
      summary: Gets a selected Person
      description: Returns a single person identified by id.
      parameters:
        - name: person_id
          in: path
          required: true
          description: Person's id
          type: number
      responses:
        '200':
          description: Returns the selected Person.
          content:
            application/json:
              schema:
                $ref: './components/person.yml#definitions/Person'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
    delete:
      tags:
        - Persons Administration
      summary: Remove a selected Person
      description: Remove a single person identified by id and return them.
      parameters:
        - name: person_id
          in: path
          required: true
          description: Person's id
          type: number
      responses:
        '204':
          description: Returns the removed Person.
          content:
            application/json:
              schema:
                $ref: './components/person.yml#definitions/RemovedPersons'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
    put:
      tags:
        - Persons Administration
      summary: Update a selected Person
      description: Update a single person identified by id and return them.
      parameters:
        - name: person_id
          in: path
          required: true
          description: Person's id
          type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components/person.yml#definitions/Person'
      responses:
        '204':
          description: return the updated person
          content:
            application/json:
              schema:
                $ref: './components/person.yml#definitions/Person'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'




